spring:
  application:
    name: expenses.tracking.api

  datasource:
    url: jdbc:postgresql://localhost:5432/expenses_company_tracker_api
    username: alexistrejo
    password: vladilena
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080

jwt:
  secret:
    key: ${JWT_SECRET_KEY}